spring:
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-2.5-flash
            temperature: 1.0
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          multiplier: 2
          max-retries: 3
        default-requeue-rejected: false
  data:
    redis:
      port: 6379
      host: localhost
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
  session:
    store-type: redis
    timeout: 7d
  mongodb:
    uri: ${MONGO_URI}
logging:
  level:
    org.springframework.boot.context.config: DEBUG
iana:
  data-base-url: ${IANA_DATA_BASE_URL}
  base-url: ${IANA_BASE_URL}
playwright:
  server:
    url: ws://localhost:3000
mail:
  from: ${GMAIL_USERNAME}
rdap:
  client:
    url: http://rdap.org
icann:
  authentication:
    base-url: https://account-api.icann.org
  account:
    username: ${ICANN_ACCOUNT_USERNAME}
    password: ${ICANN_ACCOUNT_PASSWORD}
czds:
  base-url:  https://czds-api.icann.org
  download-base-url: https://czds-download-api.icann.org
  directory: ${CZDS_DIRECTORY}